/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConsignmentNote {
  'taxes' : string,
  'truckNo' : string,
  'consignorGST' : string,
  'amountToPayRs' : string,
  'amountPaidRs' : string,
  'invoiceValue' : string,
  'consigneeAddress' : string,
  'date' : string,
  'duty' : string,
  'gcNo' : string,
  'modePacking' : string,
  'consigneeGST' : string,
  'rate' : string,
  'invoiceNo' : string,
  'description' : string,
  'consigneeName' : string,
  'consignorAddress' : string,
  'stChange' : string,
  'toCity' : string,
  'grandTotal' : string,
  'invoiceDate' : string,
  'weightActual' : string,
  'freight' : string,
  'billedTo' : string,
  'fromCity' : string,
  'noOfArticles' : string,
  'hamaali' : string,
  'amountToPayP' : string,
  'weightChanded' : string,
  'consignorName' : string,
  'amountPaidP' : string,
  'remarks' : string,
  'advance' : string,
}
export interface _SERVICE {
  'createConsignmentNote' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'getAllConsignmentNotes' : ActorMethod<[], Array<ConsignmentNote>>,
  'getConsignmentNote' : ActorMethod<[string], ConsignmentNote>,
  'getConsignmentNotesByCity' : ActorMethod<[string], Array<ConsignmentNote>>,
  'getConsignmentNotesByConsignor' : ActorMethod<
    [string],
    Array<ConsignmentNote>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];