/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ConsignmentNote {
    taxes: string;
    truckNo: string;
    consignorGST: string;
    amountToPayRs: string;
    amountPaidRs: string;
    invoiceValue: string;
    consigneeAddress: string;
    date: string;
    duty: string;
    gcNo: string;
    modePacking: string;
    consigneeGST: string;
    rate: string;
    invoiceNo: string;
    description: string;
    consigneeName: string;
    consignorAddress: string;
    stChange: string;
    toCity: string;
    grandTotal: string;
    invoiceDate: string;
    weightActual: string;
    freight: string;
    billedTo: string;
    fromCity: string;
    noOfArticles: string;
    hamaali: string;
    amountToPayP: string;
    weightChanded: string;
    consignorName: string;
    amountPaidP: string;
    remarks: string;
    advance: string;
}
export interface backendInterface {
    createConsignmentNote(gcNo: string, date: string, fromCity: string, toCity: string, truckNo: string, consignorName: string, consignorAddress: string, consignorGST: string, consigneeName: string, consigneeAddress: string, consigneeGST: string, description: string, noOfArticles: string, modePacking: string, invoiceNo: string, invoiceDate: string, invoiceValue: string, weightActual: string, weightChanded: string, rate: string, freight: string, advance: string, hamaali: string, stChange: string, duty: string, taxes: string, grandTotal: string, amountToPayRs: string, amountToPayP: string, amountPaidRs: string, amountPaidP: string, remarks: string, billedTo: string): Promise<void>;
    getAllConsignmentNotes(): Promise<Array<ConsignmentNote>>;
    getConsignmentNote(gcNo: string): Promise<ConsignmentNote>;
    getConsignmentNotesByCity(city: string): Promise<Array<ConsignmentNote>>;
    getConsignmentNotesByConsignor(consignorName: string): Promise<Array<ConsignmentNote>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createConsignmentNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string, arg14: string, arg15: string, arg16: string, arg17: string, arg18: string, arg19: string, arg20: string, arg21: string, arg22: string, arg23: string, arg24: string, arg25: string, arg26: string, arg27: string, arg28: string, arg29: string, arg30: string, arg31: string, arg32: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createConsignmentNote(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg30, arg31, arg32);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConsignmentNote(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg30, arg31, arg32);
            return result;
        }
    }
    async getAllConsignmentNotes(): Promise<Array<ConsignmentNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConsignmentNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConsignmentNotes();
            return result;
        }
    }
    async getConsignmentNote(arg0: string): Promise<ConsignmentNote> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsignmentNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsignmentNote(arg0);
            return result;
        }
    }
    async getConsignmentNotesByCity(arg0: string): Promise<Array<ConsignmentNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsignmentNotesByCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsignmentNotesByCity(arg0);
            return result;
        }
    }
    async getConsignmentNotesByConsignor(arg0: string): Promise<Array<ConsignmentNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsignmentNotesByConsignor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsignmentNotesByConsignor(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
